# Generated by Django 3.1 on 2020-08-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200826_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_text',
            field=models.TextField(blank=True),
        ),
    ]
