# Generated by Django 3.1 on 2020-10-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200930_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthmonth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='birthyear',
            field=models.IntegerField(default=2002),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.IntegerField(),
        ),
    ]
