# Generated by Django 3.1 on 2020-10-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201025_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthmonth',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthyear',
            field=models.IntegerField(blank=True, default=2020),
            preserve_default=False,
        ),
    ]
