# Generated by Django 5.0.6 on 2024-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201026_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.IntegerField(blank=True, default='0', unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthmonth',
            field=models.IntegerField(blank=True, default='0', unique_for_month=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthyear',
            field=models.IntegerField(blank=True, default='0', unique_for_year=True),
        ),
    ]
