name: Django CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Poetry
      # You may pin to the exact commit or the version.
      # uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec
      uses: Gr1N/setup-poetry@v9
      with:
        # Allow to install prerelease versions of Poetry
        poetry-preview: false # optional, default is false
        # Poetry version to use, if version is not provided then latest stable version will be used
        poetry-version: 1.8.3 # optional
    - name: Install Dependencies
      run: poetry install
    - name: Collect static
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
        AWS_DB_NAME: ${{ secrets.AWS_DB_NAME }}
        AWS_DB_USER: ${{ secrets.AWS_DB_USER }}
        AWS_DB_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}
        AWS_DB_HOST: ${{ secrets.AWS_DB_HOST }}
        AWS_DB_PORT: ${{ secrets.AWS_DB_PORT }}
      run: poetry run python manage.py collectstatic
