name: Django CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v4
    - name: Setup Poetry
      # You may pin to the exact commit or the version.
      # uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec
      uses: Gr1N/setup-poetry@v9
      with:
        # Allow to install prerelease versions of Poetry
        poetry-preview: false # optional, default is false
        # Poetry version to use, if version is not provided then latest stable version will be used
        poetry-version: 1.8.3 # optional
          
    - name: Install Dependencies
      run: |
        poetry install
        poetry run python manage.py collectstatic
